### PR TITLE
Investigate queue leak

### PR DESCRIPTION
**Pull request by TWiStErRob**

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Can you please merge or close this so I can delete my fork?

**Comment by DenBond7** [comment]
I did it. Sorry, I did not notice before. I saw your comments to https://github.com/bumptech/glide/issues/1044. Currently very busy at work. I can answer a bit later.

**Comment by TWiStErRob** [comment]
No worries, take your time. It's a hard/deep problem, and currently I'm not sure if we can fix it, luckily it only leaks until there's something new added to the queue.

**Comment by kumarbanty** [comment]
Did you guys figured some solution about this issue, I believe that I am facing something similar to this and need a way around this ASAP.

**Comment by TWiStErRob** [comment]
@kumarbanty You commented on the workaround (this is a PR), check the commit and read the related Glide issue for explanation. Of course you can drop the Logging parent class.

**Pull request merged**
